################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (9-2020-q2-update)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../Lib/paho_MQTT/Src/MQTTConnectClient.c \
../Lib/paho_MQTT/Src/MQTTConnectServer.c \
../Lib/paho_MQTT/Src/MQTTDeserializePublish.c \
../Lib/paho_MQTT/Src/MQTTFormat.c \
../Lib/paho_MQTT/Src/MQTTPacket.c \
../Lib/paho_MQTT/Src/MQTTSerializePublish.c \
../Lib/paho_MQTT/Src/MQTTSubscribeClient.c \
../Lib/paho_MQTT/Src/MQTTSubscribeServer.c \
../Lib/paho_MQTT/Src/MQTTUnsubscribeClient.c \
../Lib/paho_MQTT/Src/MQTTUnsubscribeServer.c 

OBJS += \
./Lib/paho_MQTT/Src/MQTTConnectClient.o \
./Lib/paho_MQTT/Src/MQTTConnectServer.o \
./Lib/paho_MQTT/Src/MQTTDeserializePublish.o \
./Lib/paho_MQTT/Src/MQTTFormat.o \
./Lib/paho_MQTT/Src/MQTTPacket.o \
./Lib/paho_MQTT/Src/MQTTSerializePublish.o \
./Lib/paho_MQTT/Src/MQTTSubscribeClient.o \
./Lib/paho_MQTT/Src/MQTTSubscribeServer.o \
./Lib/paho_MQTT/Src/MQTTUnsubscribeClient.o \
./Lib/paho_MQTT/Src/MQTTUnsubscribeServer.o 

C_DEPS += \
./Lib/paho_MQTT/Src/MQTTConnectClient.d \
./Lib/paho_MQTT/Src/MQTTConnectServer.d \
./Lib/paho_MQTT/Src/MQTTDeserializePublish.d \
./Lib/paho_MQTT/Src/MQTTFormat.d \
./Lib/paho_MQTT/Src/MQTTPacket.d \
./Lib/paho_MQTT/Src/MQTTSerializePublish.d \
./Lib/paho_MQTT/Src/MQTTSubscribeClient.d \
./Lib/paho_MQTT/Src/MQTTSubscribeServer.d \
./Lib/paho_MQTT/Src/MQTTUnsubscribeClient.d \
./Lib/paho_MQTT/Src/MQTTUnsubscribeServer.d 


# Each subdirectory must supply rules for building sources it contributes
Lib/paho_MQTT/Src/MQTTConnectClient.o: ../Lib/paho_MQTT/Src/MQTTConnectClient.c Lib/paho_MQTT/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F767xx -c -I../Core/Inc -I"/home/rockets/Documents/Code/ele400/ELE400EclairDeGenie/ele400f767/Lib/Pitot/Inc" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Drivers/CMSIS/Include -I../LWIP/App -I../LWIP/Target -I../Middlewares/Third_Party/LwIP/src/include -I../Middlewares/Third_Party/LwIP/system -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../Middlewares/Third_Party/LwIP/src/include/netif/ppp -I../Middlewares/Third_Party/LwIP/src/include/lwip -I../Middlewares/Third_Party/LwIP/src/include/lwip/apps -I../Middlewares/Third_Party/LwIP/src/include/lwip/priv -I../Middlewares/Third_Party/LwIP/src/include/lwip/prot -I../Middlewares/Third_Party/LwIP/src/include/netif -I../Middlewares/Third_Party/LwIP/src/include/compat/posix -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/arpa -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/net -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/sys -I../Middlewares/Third_Party/LwIP/src/include/compat/stdc -I../Middlewares/Third_Party/LwIP/system/arch -I"/home/rockets/Documents/Code/ele400/ELE400EclairDeGenie/ele400f767/Lib/Client_MQTT/Inc" -I"/home/rockets/Documents/Code/ele400/ELE400EclairDeGenie/ele400f767/Lib/debug_interface/Inc" -I"/home/rockets/Documents/Code/ele400/ELE400EclairDeGenie/ele400f767/Lib/Node_MQTT/Inc" -I"/home/rockets/Documents/Code/ele400/ELE400EclairDeGenie/ele400f767/Lib/paho_MQTT/Inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Lib/paho_MQTT/Src/MQTTConnectClient.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Lib/paho_MQTT/Src/MQTTConnectServer.o: ../Lib/paho_MQTT/Src/MQTTConnectServer.c Lib/paho_MQTT/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F767xx -c -I../Core/Inc -I"/home/rockets/Documents/Code/ele400/ELE400EclairDeGenie/ele400f767/Lib/Pitot/Inc" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Drivers/CMSIS/Include -I../LWIP/App -I../LWIP/Target -I../Middlewares/Third_Party/LwIP/src/include -I../Middlewares/Third_Party/LwIP/system -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../Middlewares/Third_Party/LwIP/src/include/netif/ppp -I../Middlewares/Third_Party/LwIP/src/include/lwip -I../Middlewares/Third_Party/LwIP/src/include/lwip/apps -I../Middlewares/Third_Party/LwIP/src/include/lwip/priv -I../Middlewares/Third_Party/LwIP/src/include/lwip/prot -I../Middlewares/Third_Party/LwIP/src/include/netif -I../Middlewares/Third_Party/LwIP/src/include/compat/posix -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/arpa -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/net -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/sys -I../Middlewares/Third_Party/LwIP/src/include/compat/stdc -I../Middlewares/Third_Party/LwIP/system/arch -I"/home/rockets/Documents/Code/ele400/ELE400EclairDeGenie/ele400f767/Lib/Client_MQTT/Inc" -I"/home/rockets/Documents/Code/ele400/ELE400EclairDeGenie/ele400f767/Lib/debug_interface/Inc" -I"/home/rockets/Documents/Code/ele400/ELE400EclairDeGenie/ele400f767/Lib/Node_MQTT/Inc" -I"/home/rockets/Documents/Code/ele400/ELE400EclairDeGenie/ele400f767/Lib/paho_MQTT/Inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Lib/paho_MQTT/Src/MQTTConnectServer.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Lib/paho_MQTT/Src/MQTTDeserializePublish.o: ../Lib/paho_MQTT/Src/MQTTDeserializePublish.c Lib/paho_MQTT/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F767xx -c -I../Core/Inc -I"/home/rockets/Documents/Code/ele400/ELE400EclairDeGenie/ele400f767/Lib/Pitot/Inc" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Drivers/CMSIS/Include -I../LWIP/App -I../LWIP/Target -I../Middlewares/Third_Party/LwIP/src/include -I../Middlewares/Third_Party/LwIP/system -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../Middlewares/Third_Party/LwIP/src/include/netif/ppp -I../Middlewares/Third_Party/LwIP/src/include/lwip -I../Middlewares/Third_Party/LwIP/src/include/lwip/apps -I../Middlewares/Third_Party/LwIP/src/include/lwip/priv -I../Middlewares/Third_Party/LwIP/src/include/lwip/prot -I../Middlewares/Third_Party/LwIP/src/include/netif -I../Middlewares/Third_Party/LwIP/src/include/compat/posix -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/arpa -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/net -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/sys -I../Middlewares/Third_Party/LwIP/src/include/compat/stdc -I../Middlewares/Third_Party/LwIP/system/arch -I"/home/rockets/Documents/Code/ele400/ELE400EclairDeGenie/ele400f767/Lib/Client_MQTT/Inc" -I"/home/rockets/Documents/Code/ele400/ELE400EclairDeGenie/ele400f767/Lib/debug_interface/Inc" -I"/home/rockets/Documents/Code/ele400/ELE400EclairDeGenie/ele400f767/Lib/Node_MQTT/Inc" -I"/home/rockets/Documents/Code/ele400/ELE400EclairDeGenie/ele400f767/Lib/paho_MQTT/Inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Lib/paho_MQTT/Src/MQTTDeserializePublish.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Lib/paho_MQTT/Src/MQTTFormat.o: ../Lib/paho_MQTT/Src/MQTTFormat.c Lib/paho_MQTT/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F767xx -c -I../Core/Inc -I"/home/rockets/Documents/Code/ele400/ELE400EclairDeGenie/ele400f767/Lib/Pitot/Inc" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Drivers/CMSIS/Include -I../LWIP/App -I../LWIP/Target -I../Middlewares/Third_Party/LwIP/src/include -I../Middlewares/Third_Party/LwIP/system -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../Middlewares/Third_Party/LwIP/src/include/netif/ppp -I../Middlewares/Third_Party/LwIP/src/include/lwip -I../Middlewares/Third_Party/LwIP/src/include/lwip/apps -I../Middlewares/Third_Party/LwIP/src/include/lwip/priv -I../Middlewares/Third_Party/LwIP/src/include/lwip/prot -I../Middlewares/Third_Party/LwIP/src/include/netif -I../Middlewares/Third_Party/LwIP/src/include/compat/posix -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/arpa -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/net -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/sys -I../Middlewares/Third_Party/LwIP/src/include/compat/stdc -I../Middlewares/Third_Party/LwIP/system/arch -I"/home/rockets/Documents/Code/ele400/ELE400EclairDeGenie/ele400f767/Lib/Client_MQTT/Inc" -I"/home/rockets/Documents/Code/ele400/ELE400EclairDeGenie/ele400f767/Lib/debug_interface/Inc" -I"/home/rockets/Documents/Code/ele400/ELE400EclairDeGenie/ele400f767/Lib/Node_MQTT/Inc" -I"/home/rockets/Documents/Code/ele400/ELE400EclairDeGenie/ele400f767/Lib/paho_MQTT/Inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Lib/paho_MQTT/Src/MQTTFormat.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Lib/paho_MQTT/Src/MQTTPacket.o: ../Lib/paho_MQTT/Src/MQTTPacket.c Lib/paho_MQTT/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F767xx -c -I../Core/Inc -I"/home/rockets/Documents/Code/ele400/ELE400EclairDeGenie/ele400f767/Lib/Pitot/Inc" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Drivers/CMSIS/Include -I../LWIP/App -I../LWIP/Target -I../Middlewares/Third_Party/LwIP/src/include -I../Middlewares/Third_Party/LwIP/system -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../Middlewares/Third_Party/LwIP/src/include/netif/ppp -I../Middlewares/Third_Party/LwIP/src/include/lwip -I../Middlewares/Third_Party/LwIP/src/include/lwip/apps -I../Middlewares/Third_Party/LwIP/src/include/lwip/priv -I../Middlewares/Third_Party/LwIP/src/include/lwip/prot -I../Middlewares/Third_Party/LwIP/src/include/netif -I../Middlewares/Third_Party/LwIP/src/include/compat/posix -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/arpa -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/net -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/sys -I../Middlewares/Third_Party/LwIP/src/include/compat/stdc -I../Middlewares/Third_Party/LwIP/system/arch -I"/home/rockets/Documents/Code/ele400/ELE400EclairDeGenie/ele400f767/Lib/Client_MQTT/Inc" -I"/home/rockets/Documents/Code/ele400/ELE400EclairDeGenie/ele400f767/Lib/debug_interface/Inc" -I"/home/rockets/Documents/Code/ele400/ELE400EclairDeGenie/ele400f767/Lib/Node_MQTT/Inc" -I"/home/rockets/Documents/Code/ele400/ELE400EclairDeGenie/ele400f767/Lib/paho_MQTT/Inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Lib/paho_MQTT/Src/MQTTPacket.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Lib/paho_MQTT/Src/MQTTSerializePublish.o: ../Lib/paho_MQTT/Src/MQTTSerializePublish.c Lib/paho_MQTT/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F767xx -c -I../Core/Inc -I"/home/rockets/Documents/Code/ele400/ELE400EclairDeGenie/ele400f767/Lib/Pitot/Inc" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Drivers/CMSIS/Include -I../LWIP/App -I../LWIP/Target -I../Middlewares/Third_Party/LwIP/src/include -I../Middlewares/Third_Party/LwIP/system -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../Middlewares/Third_Party/LwIP/src/include/netif/ppp -I../Middlewares/Third_Party/LwIP/src/include/lwip -I../Middlewares/Third_Party/LwIP/src/include/lwip/apps -I../Middlewares/Third_Party/LwIP/src/include/lwip/priv -I../Middlewares/Third_Party/LwIP/src/include/lwip/prot -I../Middlewares/Third_Party/LwIP/src/include/netif -I../Middlewares/Third_Party/LwIP/src/include/compat/posix -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/arpa -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/net -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/sys -I../Middlewares/Third_Party/LwIP/src/include/compat/stdc -I../Middlewares/Third_Party/LwIP/system/arch -I"/home/rockets/Documents/Code/ele400/ELE400EclairDeGenie/ele400f767/Lib/Client_MQTT/Inc" -I"/home/rockets/Documents/Code/ele400/ELE400EclairDeGenie/ele400f767/Lib/debug_interface/Inc" -I"/home/rockets/Documents/Code/ele400/ELE400EclairDeGenie/ele400f767/Lib/Node_MQTT/Inc" -I"/home/rockets/Documents/Code/ele400/ELE400EclairDeGenie/ele400f767/Lib/paho_MQTT/Inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Lib/paho_MQTT/Src/MQTTSerializePublish.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Lib/paho_MQTT/Src/MQTTSubscribeClient.o: ../Lib/paho_MQTT/Src/MQTTSubscribeClient.c Lib/paho_MQTT/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F767xx -c -I../Core/Inc -I"/home/rockets/Documents/Code/ele400/ELE400EclairDeGenie/ele400f767/Lib/Pitot/Inc" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Drivers/CMSIS/Include -I../LWIP/App -I../LWIP/Target -I../Middlewares/Third_Party/LwIP/src/include -I../Middlewares/Third_Party/LwIP/system -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../Middlewares/Third_Party/LwIP/src/include/netif/ppp -I../Middlewares/Third_Party/LwIP/src/include/lwip -I../Middlewares/Third_Party/LwIP/src/include/lwip/apps -I../Middlewares/Third_Party/LwIP/src/include/lwip/priv -I../Middlewares/Third_Party/LwIP/src/include/lwip/prot -I../Middlewares/Third_Party/LwIP/src/include/netif -I../Middlewares/Third_Party/LwIP/src/include/compat/posix -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/arpa -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/net -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/sys -I../Middlewares/Third_Party/LwIP/src/include/compat/stdc -I../Middlewares/Third_Party/LwIP/system/arch -I"/home/rockets/Documents/Code/ele400/ELE400EclairDeGenie/ele400f767/Lib/Client_MQTT/Inc" -I"/home/rockets/Documents/Code/ele400/ELE400EclairDeGenie/ele400f767/Lib/debug_interface/Inc" -I"/home/rockets/Documents/Code/ele400/ELE400EclairDeGenie/ele400f767/Lib/Node_MQTT/Inc" -I"/home/rockets/Documents/Code/ele400/ELE400EclairDeGenie/ele400f767/Lib/paho_MQTT/Inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Lib/paho_MQTT/Src/MQTTSubscribeClient.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Lib/paho_MQTT/Src/MQTTSubscribeServer.o: ../Lib/paho_MQTT/Src/MQTTSubscribeServer.c Lib/paho_MQTT/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F767xx -c -I../Core/Inc -I"/home/rockets/Documents/Code/ele400/ELE400EclairDeGenie/ele400f767/Lib/Pitot/Inc" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Drivers/CMSIS/Include -I../LWIP/App -I../LWIP/Target -I../Middlewares/Third_Party/LwIP/src/include -I../Middlewares/Third_Party/LwIP/system -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../Middlewares/Third_Party/LwIP/src/include/netif/ppp -I../Middlewares/Third_Party/LwIP/src/include/lwip -I../Middlewares/Third_Party/LwIP/src/include/lwip/apps -I../Middlewares/Third_Party/LwIP/src/include/lwip/priv -I../Middlewares/Third_Party/LwIP/src/include/lwip/prot -I../Middlewares/Third_Party/LwIP/src/include/netif -I../Middlewares/Third_Party/LwIP/src/include/compat/posix -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/arpa -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/net -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/sys -I../Middlewares/Third_Party/LwIP/src/include/compat/stdc -I../Middlewares/Third_Party/LwIP/system/arch -I"/home/rockets/Documents/Code/ele400/ELE400EclairDeGenie/ele400f767/Lib/Client_MQTT/Inc" -I"/home/rockets/Documents/Code/ele400/ELE400EclairDeGenie/ele400f767/Lib/debug_interface/Inc" -I"/home/rockets/Documents/Code/ele400/ELE400EclairDeGenie/ele400f767/Lib/Node_MQTT/Inc" -I"/home/rockets/Documents/Code/ele400/ELE400EclairDeGenie/ele400f767/Lib/paho_MQTT/Inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Lib/paho_MQTT/Src/MQTTSubscribeServer.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Lib/paho_MQTT/Src/MQTTUnsubscribeClient.o: ../Lib/paho_MQTT/Src/MQTTUnsubscribeClient.c Lib/paho_MQTT/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F767xx -c -I../Core/Inc -I"/home/rockets/Documents/Code/ele400/ELE400EclairDeGenie/ele400f767/Lib/Pitot/Inc" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Drivers/CMSIS/Include -I../LWIP/App -I../LWIP/Target -I../Middlewares/Third_Party/LwIP/src/include -I../Middlewares/Third_Party/LwIP/system -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../Middlewares/Third_Party/LwIP/src/include/netif/ppp -I../Middlewares/Third_Party/LwIP/src/include/lwip -I../Middlewares/Third_Party/LwIP/src/include/lwip/apps -I../Middlewares/Third_Party/LwIP/src/include/lwip/priv -I../Middlewares/Third_Party/LwIP/src/include/lwip/prot -I../Middlewares/Third_Party/LwIP/src/include/netif -I../Middlewares/Third_Party/LwIP/src/include/compat/posix -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/arpa -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/net -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/sys -I../Middlewares/Third_Party/LwIP/src/include/compat/stdc -I../Middlewares/Third_Party/LwIP/system/arch -I"/home/rockets/Documents/Code/ele400/ELE400EclairDeGenie/ele400f767/Lib/Client_MQTT/Inc" -I"/home/rockets/Documents/Code/ele400/ELE400EclairDeGenie/ele400f767/Lib/debug_interface/Inc" -I"/home/rockets/Documents/Code/ele400/ELE400EclairDeGenie/ele400f767/Lib/Node_MQTT/Inc" -I"/home/rockets/Documents/Code/ele400/ELE400EclairDeGenie/ele400f767/Lib/paho_MQTT/Inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Lib/paho_MQTT/Src/MQTTUnsubscribeClient.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Lib/paho_MQTT/Src/MQTTUnsubscribeServer.o: ../Lib/paho_MQTT/Src/MQTTUnsubscribeServer.c Lib/paho_MQTT/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F767xx -c -I../Core/Inc -I"/home/rockets/Documents/Code/ele400/ELE400EclairDeGenie/ele400f767/Lib/Pitot/Inc" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Drivers/CMSIS/Include -I../LWIP/App -I../LWIP/Target -I../Middlewares/Third_Party/LwIP/src/include -I../Middlewares/Third_Party/LwIP/system -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../Middlewares/Third_Party/LwIP/src/include/netif/ppp -I../Middlewares/Third_Party/LwIP/src/include/lwip -I../Middlewares/Third_Party/LwIP/src/include/lwip/apps -I../Middlewares/Third_Party/LwIP/src/include/lwip/priv -I../Middlewares/Third_Party/LwIP/src/include/lwip/prot -I../Middlewares/Third_Party/LwIP/src/include/netif -I../Middlewares/Third_Party/LwIP/src/include/compat/posix -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/arpa -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/net -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/sys -I../Middlewares/Third_Party/LwIP/src/include/compat/stdc -I../Middlewares/Third_Party/LwIP/system/arch -I"/home/rockets/Documents/Code/ele400/ELE400EclairDeGenie/ele400f767/Lib/Client_MQTT/Inc" -I"/home/rockets/Documents/Code/ele400/ELE400EclairDeGenie/ele400f767/Lib/debug_interface/Inc" -I"/home/rockets/Documents/Code/ele400/ELE400EclairDeGenie/ele400f767/Lib/Node_MQTT/Inc" -I"/home/rockets/Documents/Code/ele400/ELE400EclairDeGenie/ele400f767/Lib/paho_MQTT/Inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Lib/paho_MQTT/Src/MQTTUnsubscribeServer.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"

